// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderSelector(arg1) {
  return window['go']['main']['App']['FolderSelector'](arg1);
}

export function RunDeletion(arg1, arg2) {
  return window['go']['main']['App']['RunDeletion'](arg1, arg2);
}
