// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderSelector(arg1:string):Promise<string>;

export function RunDeletion(arg1:string,arg2:string):Promise<string>;
